name: Build Release APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - run: npm install -g cordova
      
      - name: Create and Configure Project
        run: |
          cordova create app com.nexus.store "Nexus Store"
          cp config.xml app/
          rm app/www/index.html
          cp index.html app/www/
          # Copia chaves e configuracao
          cp build.json app/
          cp nexus.keystore app/

      - working-directory: ./app
        run: cordova platform add android
        
      - name: Build and Sign
        working-directory: ./app
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          # O flag --buildConfig forca o uso da sua chave
          cordova build android --release --buildConfig=build.json
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexus-store-apk
          # O asterisco (*) pega QUALQUER apk gerado na pasta release
          path: app/platforms/android/app/build/outputs/apk/release/*.apk
